#%RAML 1.0
title: ACME Banking API
description: This API offers access to personal banking data, around customers, transactions and accounts. GitHub Signed!
mediaType:
  - application/json
version: v1
protocols:
  - HTTPS
  - HTTP
# Register new datatypes
types:
  Account: !include datatypes/Account.raml


/accounts:
  post:
    displayName: Create a new account
    body:
      type: Account
    responses:
      201:
      400:
        headers: 
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: Body is missing the account ID.

  /{account_id}:
    get:
      displayName: Get account information for a specific account ID
      headers:
        Accept: 
          example: application/json
      responses:
        200:
          headers:
            Cache-Control:
              example: max-age=604800 # 1 week
        
    put:
      displayName: Update account information for a specific account ID
      responses:
        201:
        503:
          headers: 
          body:
            example:
              type: Service Unavailable
              title: Service Unavailable
              detail: The account service is not available.
    delete:
      displayName: Delete an account with a specific account ID
      responses:
        202:
        204:
    
    /transactions:
      get:
        displayName: Get all transactions for a specific account ID
        headers:
          Accept: 
            example: application/json
        responses:
          200:
            headers:
              Cache-Control:
                example: max-age=604800 # 1 week

/customers:
  post:
    displayName: Create a new customer
    responses:
      201:
      400:
        headers: 
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: Body is missing the account ID.
  get:
    displayName: Get all customers in the bank
    # headers & body for request
    headers:
      Accept: 
        example: application/json          
          
    responses:
        200:
          headers:
            Cache-Control:
              example: max-age=604800 # 1 week

  
  /{customer_id}:
    get:
      displayName: Get customer information for a specific customer ID  
      headers:
        Accept: 
          example: application/json
      responses:
        200:
          headers:
            Cache-Control:
              example: max-age=604800 # 1 week
    patch:
      displayName: Update customer information for a specific customer ID
      responses:
        204:
        503:
          headers: 
          body:
            example:
              type: Service Unavailable
              title: Service Unavailable
              detail: The account service is not available.
    delete:
      displayName: Delete a customer with a specific customer ID
      responses:
        202:
        204:

    /accounts:
      get:
        displayName: Get all accounts for a specific customer ID
        headers:
          Accept: 
            example: application/json
        responses:
          200:
            headers:
              Cache-Control:
                example: max-age=604800 # 1 week
  

/transactions:
  post:
    displayName: Create a new transaction
    responses:
      201:
      400:
        headers: 
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: Body is missing the account ID.
  
  /{transaction_id}:
    get:
      displayName: Get transaction information for a specific transaction ID
      headers:
        Accept: 
          example: application/json
      responses:
        200:
          headers:
            Cache-Control:
              example: max-age=604800 # 1 week

