#%RAML 1.0
title: ACME Banking API
description: This API offers access to personal banking data, around customers, transactions and accounts. GitHub Signed!
mediaType:
  - application/json
version: v1
protocols:
  - HTTPS
  - HTTP


/accounts:
  post:
    displayName: Create a new account
    responses:
      201:
      400:
        headers:
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: I

  /{account_id}:
    get:
      displayName: Get account information for a specific account ID
      responses:
        200:
    put:
      displayName: Update account information for a specific account ID
      responses:
        201:
    delete:
      displayName: Delete an account with a specific account ID
      responses:
        202:
        204:
    
    /transactions:
      get:
        displayName: Get all transactions for a specific account ID
        responses:
          200:

/customers:
  post:
    displayName: Create a new customer
    responses:
      201:
  get:
    displayName: Get all customers in the bank
    responses:
        200:
  
  /{customer_id}:
    get:
      displayName: Get customer information for a specific customer ID  
      responses:
        200:
    patch:
      displayName: Update customer information for a specific customer ID
      responses:
        204:
    delete:
      displayName: Delete a customer with a specific customer ID
      responses:
        202:
        204:

    /accounts:
      get:
        displayName: Get all accounts for a specific customer ID
        responses:
          200:
  

/transactions:
  post:
    displayName: Create a new transaction
    responses:
      201:
  
  /{transaction_id}:
    get:
      displayName: Get transaction information for a specific transaction ID
      responses:
        200:

