#%RAML 1.0
title: ACME Banking API
description: This API offers access to personal banking data, around customers, transactions and accounts.
mediaType:
  - application/json
version: v1
protocols:
  - HTTPS
  - HTTP


/accounts:
  post:
    displayName: Create a new account

  /{account_id}:
    get:
      displayName: Get account information for a specific account ID
    put:
      displayName: Update account information for a specific account ID
    delete:
      displayName: Delete an account with a specific account ID
    
    /transactions:
      get:
        displayName: Get all transactions for a specific account ID

/customers:
  post:
    displayName: Create a new customer
  get:
    displayName: Get all customers in the bank
  
  /{customer_id}:
    get:
      displayName: Get customer information for a specific customer ID  
    patch:
      displayName: Update customer information for a specific customer ID
    delete:
      displayName: Delete a customer with a specific customer ID

    /accounts:
      get:
        displayName: Get all accounts for a specific customer ID
  

/transactions:
  post:
    displayName: Create a new transaction
  
  /{transaction_id}:
    get:
      displayName: Get transaction information for a specific transaction ID

