#%RAML 1.0 NamedExample
CustomerExample:
  customerID: 8f19cb50-3f57-4d38
  firstName: joão
  lastName: da Silva
  displayName: João da Silva
  address: 
    addressLine1: Fake Street 99
    addressLine2: Apt.#123
    city: San Diego
    state: California
    zipCode: '94229'
    country: United States
  phone: 415-000-0000
  email: jsilva@example.com
  ssn: 123-45-7890
  dateOfBirth: 1985-01-01
